# -*- coding: utf-8 -*-
"""alert_anomaly_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7gyPLzByme0GEFK1McQExcfZInO2EV5
"""
# use panda to load dataset
import pandas as pd
import numpy as np
df = pd.read_csv('mcp_servers/hard_training_data.csv')
df.head()

df.info()

df_raw = df.copy()

identity_columns = ["alert_id","service_name","environment","timestamp"]
metric_columns = ["cpu_usage","memory_usage","incoming_traffic","outgoing_traffic","error_rate","retry_rate","timeout_count","network_throughput","request_rate","response_latency","availability_percent","log_repetition_count"]
label_column = "label"

print(df_raw["label"].value_counts())
print(df_raw["label"].value_counts(normalize=True))

print(df_raw[metric_columns].describe().T)

print(df_raw[metric_columns].nunique())

df_metrics = df_raw.melt(
    id_vars=identity_columns + [label_column],
    value_vars=metric_columns,
    var_name="metric_name",
    value_name="metric_value"
)

print("-----------------metrics info-----------------")
print(df_metrics.info())
print("-----------------metrics head-----------------")
print(df_metrics.head())

# ============================================
# 1. Sort by timestamp
# ============================================

df_raw["timestamp"] = pd.to_datetime(df_raw["timestamp"])
df_raw = df_raw.sort_values("timestamp").reset_index(drop=True)


# ============================================
# 2. Time-based train/test split
# ============================================

split_index = int(len(df_raw) * 0.85)

df_train_raw = df_raw.iloc[:split_index].copy()
df_test_raw = df_raw.iloc[split_index:].copy()

print("Train:", len(df_train_raw))
print("Test :", len(df_test_raw))


# ============================================
# 3. Metric columns
# ============================================

metric_columns = [
    "cpu_usage",
    "memory_usage",
    "incoming_traffic",
    "outgoing_traffic",
    "error_rate",
    "retry_rate",
    "timeout_count",
    "network_throughput",
    "request_rate",
    "response_latency",
    "availability_percent",
    "log_repetition_count"
]


# ============================================
# 4. Melt TRAIN and TEST separately
# ============================================

df_train_metrics = df_train_raw.melt(
    id_vars=[
        "alert_id",
        "service_name",
        "environment",
        "timestamp",
        "label"
    ],
    value_vars=metric_columns,
    var_name="metric_name",
    value_name="metric_value"
)

df_test_metrics = df_test_raw.melt(
    id_vars=[
        "alert_id",
        "service_name",
        "environment",
        "timestamp",
        "label"
    ],
    value_vars=metric_columns,
    var_name="metric_name",
    value_name="metric_value"
)


# ============================================
# 5. Calculate BASELINE from TRAIN ONLY
# ============================================

baseline = (
    df_train_metrics
    .groupby("metric_name")["metric_value"]
    .agg(
        median="median",
        q1=lambda x: x.quantile(0.25),
        q3=lambda x: x.quantile(0.75)
    )
    .reset_index()
)

baseline["iqr"] = baseline["q3"] - baseline["q1"]

baseline["lower_bound"] = (
    baseline["q1"] - 1.5 * baseline["iqr"]
)

baseline["upper_bound"] = (
    baseline["q3"] + 1.5 * baseline["iqr"]
)


# ============================================
# 6. Apply SAME baseline to TRAIN
# ============================================

df_train_metrics_baseline = df_train_metrics.merge(
    baseline,
    on="metric_name",
    how="left"
)


# ============================================
# 7. Apply SAME baseline to TEST
# ============================================

df_test_metrics_baseline = df_test_metrics.merge(
    baseline,
    on="metric_name",
    how="left"
)


# ============================================
# 8. Check
# ============================================

print("Train metrics:", df_train_metrics_baseline.shape)
print("Test metrics :", df_test_metrics_baseline.shape)

# display(baseline)
# display(df_train_metrics_baseline.head())
# display(df_test_metrics_baseline.head())

def add_metric_features(df):
    df = df.copy()

    # Avoid division by zero
    safe_iqr = df["iqr"].replace(0, np.nan)

    # Distance from baseline median, normalized by IQR
    df["robust_deviation"] = (
        (df["metric_value"] - df["median"]).abs()
        / safe_iqr
    )

    # Relative change from baseline median
    safe_median = df["median"].replace(0, np.nan)

    df["relative_change"] = (
        (df["metric_value"] - df["median"])
        / safe_median
    )

    # Whether metric falls outside training baseline bounds
    df["is_outlier"] = (
        (df["metric_value"] < df["lower_bound"]) |
        (df["metric_value"] > df["upper_bound"])
    ).astype(int)

    # Direction of deviation
    df["direction"] = np.where(
        df["metric_value"] > df["median"],
        "above",
        "below"
    )

    return df

def create_alert_features(df):
    alert_features = (
        df.groupby("alert_id")
        .agg(
            metric_count=("metric_name", "count"),
            baseline_coverage=("median", lambda x: x.notna().mean()),

            mean_deviation=("robust_deviation", "mean"),
            max_deviation=("robust_deviation", "max"),

            outlier_count=("is_outlier", "sum"),
            outlier_ratio=("is_outlier", "mean"),

            mean_relative_change=("relative_change", "mean"),
            max_relative_change=(
                "relative_change",
                lambda x: x.abs().max()
            ),

            above_ratio=(
                "direction",
                lambda x: (x == "above").mean()
            ),

            below_ratio=(
                "direction",
                lambda x: (x == "below").mean()
            ),
        )
        .reset_index()
    )

    return alert_features

def add_alert_anomaly_features(alert_features, df_metrics):
    anomaly_concentration = (
        df_metrics[df_metrics["is_outlier"] == 1]
        .groupby("alert_id")["robust_deviation"]
        .mean()
        .rename("anomaly_concentration")
    )

    anomalous_metric_count = (
        df_metrics
        .groupby("alert_id")["is_outlier"]
        .sum()
        .rename("anomalous_metric_count")
    )

    alert_features = alert_features.merge(
        anomaly_concentration,
        on="alert_id",
        how="left"
    )

    alert_features = alert_features.merge(
        anomalous_metric_count,
        on="alert_id",
        how="left"
    )

    # No anomalous metrics → concentration = 0
    alert_features["anomaly_concentration"] = (
        alert_features["anomaly_concentration"]
        .fillna(0)
    )

    alert_features["anomalous_metric_count"] = (
        alert_features["anomalous_metric_count"]
        .fillna(0)
    )

    return alert_features

# 1. Metric-level feature engineering
df_metrics_train_baseline = add_metric_features(df_train_metrics_baseline)
df_metrics_test_baseline = add_metric_features(df_test_metrics_baseline)

# 2. Create normal alert-level features
alert_features_train_monitor = create_alert_features(df_metrics_train_baseline)
alert_features_test_monitor = create_alert_features(df_metrics_test_baseline)

# 3. Add new anomaly-specific features
alert_features_train = add_alert_anomaly_features(
    alert_features_train_monitor,
    df_metrics_train_baseline
)
alert_features_test = add_alert_anomaly_features(
    alert_features_test_monitor,
    df_metrics_test_baseline
)

# 4. Add labels
train_labels = (
    df_train_raw[
        ["alert_id", "label"]
    ]
    .drop_duplicates("alert_id")
)

test_labels = (
    df_test_raw[
        ["alert_id", "label"]
    ]
    .drop_duplicates("alert_id")
)

alert_train_features = alert_features_train.merge(
    train_labels,
    on="alert_id",
    how="left"
)

alert_test_features = alert_features_test.merge(
    test_labels,
    on="alert_id",
    how="left"
)

new_features = [
    "metric_count",
    "baseline_coverage",
    "mean_deviation",
    "max_deviation",
    "outlier_count",
    "outlier_ratio",
    "mean_relative_change",
    "max_relative_change",
    "above_ratio",
    "below_ratio",
    "anomaly_concentration",
    "anomalous_metric_count"
]

# display(
#     alert_features[new_features + ["label"]].head(20)
# )

# for feature in [
#     "anomaly_concentration",
#     "anomalous_metric_count"
# ]:
#     print(f"\n===== {feature} =====")

#     print(
#         alert_features
#         .groupby("label")[feature]
#         .describe()
#     )

# inspect_features = [
#     "mean_deviation",
#     "max_deviation",
#     "outlier_ratio",
#     "mean_relative_change",
#     "max_relative_change",
#     "above_ratio",
#     "below_ratio",
#     "anomalous_metric_count",
#     "anomaly_concentration",
# ]

set3_features = [
    "mean_deviation",
    "max_deviation",
    "outlier_ratio",
    "mean_relative_change",
    "max_relative_change",
    "anomalous_metric_count",
    "anomaly_concentration",
]

# for feature in inspect_features:
#     print(f"\n===== {feature} =====")
#     display(
#         alert_features
#         .groupby("label")[feature]
#         .describe()
#     )

# train_labels = (
#     df_train_raw[
#         ["alert_id", "label"]
#     ]
#     .drop_duplicates("alert_id")
# )

# test_labels = (
#     df_test_raw[
#         ["alert_id", "label"]
#     ]
#     .drop_duplicates("alert_id")
# )

# alert_train_features = alert_features.merge(
#     train_labels,
#     on="alert_id",
#     how="left"
# )

# alert_test_features = alert_features.merge(
#     test_labels,
#     on="alert_id",
#     how="left"
# )

X_train = alert_train_features[set3_features]
y_train = alert_train_features["label"]

X_test = alert_test_features[set3_features]
y_test = alert_test_features["label"]

print(X_train.shape)
print(X_test.shape)

print(y_train.value_counts())
print(y_test.value_counts())

from sklearn.ensemble import IsolationForest

iso_forest = IsolationForest(
    n_estimators=300,
    contamination="auto",
    random_state=42,
    n_jobs=-1
)

iso_forest.fit(X_train)

train_pred = iso_forest.predict(X_train)
test_pred = iso_forest.predict(X_test)

train_anomaly = (train_pred == -1).astype(int)
test_anomaly = (test_pred == -1).astype(int)

print("Train anomalies:")
print(pd.Series(train_anomaly).value_counts())

print("\nTest anomalies:")
print(pd.Series(test_anomaly).value_counts())

y_train_anomaly = (y_train == 0).astype(int)
y_test_anomaly = (y_test == 0).astype(int)

from sklearn.metrics import classification_report, confusion_matrix

print("TRAIN")
print(confusion_matrix(y_train_anomaly, train_anomaly))
print(classification_report(y_train_anomaly, train_anomaly))

print("\nTEST")
print("Confusion Matrix:")
print(confusion_matrix(y_test_anomaly, test_anomaly))
print("\nClassification Report:")
print(classification_report(y_test_anomaly, test_anomaly, target_names=[
            "False Alert",
            "True Alert"
        ]))

test_results = alert_test_features[
    ["alert_id"] + set3_features + ["label"]
].copy()

test_results["ml_anomaly"] = test_anomaly
test_results["anomaly_score"] = iso_forest.decision_function(X_test)
false_anomalies = test_results[
    (test_results["label"] == 1) &
    (test_results["ml_anomaly"] == 1)
]

# display(
#     test_results[
#         [
#             "alert_id",
#             "label",
#             "ml_anomaly",
#             "anomaly_score",
#             "mean_deviation",
#             "max_deviation",
#             "outlier_ratio",
#             "mean_relative_change",
#             "max_relative_change"
#         ]
#     ]
#     .sort_values("anomaly_score")
#     .head(25)
# )

true_positive = test_results[
    (test_results["label"] == 0) &
    (test_results["ml_anomaly"] == 1)
]

print("False positives:", len(false_anomalies))
print("True positives:", len(true_positive))

false_negatives = test_results[
    (test_results["label"] == 0) &
    (test_results["ml_anomaly"] == 1)
]

print("False negatives:", len(false_negatives))

# display(
#     false_negatives[
#         [
#             "alert_id",
#             "label",
#             "ml_anomaly",
#             "anomaly_score",
#             "mean_deviation",
#             "max_deviation",
#             "outlier_ratio",
#             "mean_relative_change",
#             "max_relative_change",
#             "anomalous_metric_count",
#             "anomaly_concentration"
#         ]
#     ]
# )

comparison_features = [
    "mean_deviation",
    "max_deviation",
    "outlier_ratio",
    "mean_relative_change",
    "max_relative_change",
    "above_ratio",
    "below_ratio",
    "anomalous_metric_count",
    "anomaly_concentration",
]

comparison = pd.DataFrame({
    "False Positive": false_anomalies[comparison_features].mean(),
    "True Positive": true_positive[comparison_features].mean()
})

# display(comparison)

pd.crosstab(
    alert_train_features["anomalous_metric_count"],
    alert_train_features["label"],
    margins=True
)
pd.crosstab(
    alert_train_features["outlier_ratio"] > 0,
    alert_train_features["label"],
    margins=True
)
pd.crosstab(
    alert_train_features["anomaly_concentration"] > 0,
    alert_train_features["label"],
    margins=True
)

