// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/WillieBam/support_copilot/backend/types/models"

	types "github.com/WillieBam/support_copilot/backend/types"

	uuid "github.com/google/uuid"
)

// IAuthService is an autogenerated mock type for the IAuthService type
type IAuthService struct {
	mock.Mock
}

// DisableTOTP provides a mock function with given fields: ctx, userID
func (_m *IAuthService) DisableTOTP(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DisableTOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExchangeToken provides a mock function with given fields: ctx, firebaseToken, totpCode
func (_m *IAuthService) ExchangeToken(ctx context.Context, firebaseToken string, totpCode string) (string, *types.Claims, error) {
	ret := _m.Called(ctx, firebaseToken, totpCode)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeToken")
	}

	var r0 string
	var r1 *types.Claims
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, *types.Claims, error)); ok {
		return rf(ctx, firebaseToken, totpCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, firebaseToken, totpCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *types.Claims); ok {
		r1 = rf(ctx, firebaseToken, totpCode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Claims)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, firebaseToken, totpCode)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LoginWithPassword provides a mock function with given fields: ctx, usernameOrEmail, password, totpCode
func (_m *IAuthService) LoginWithPassword(ctx context.Context, usernameOrEmail string, password string, totpCode string) (string, *types.Claims, error) {
	ret := _m.Called(ctx, usernameOrEmail, password, totpCode)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithPassword")
	}

	var r0 string
	var r1 *types.Claims
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, *types.Claims, error)); ok {
		return rf(ctx, usernameOrEmail, password, totpCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, usernameOrEmail, password, totpCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) *types.Claims); ok {
		r1 = rf(ctx, usernameOrEmail, password, totpCode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Claims)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, usernameOrEmail, password, totpCode)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ParseAndValidateAuthToken provides a mock function with given fields: ctx, tokenString
func (_m *IAuthService) ParseAndValidateAuthToken(ctx context.Context, tokenString string) (*types.Claims, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseAndValidateAuthToken")
	}

	var r0 *types.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*types.Claims, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *types.Claims); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, username, email, password
func (_m *IAuthService) Register(ctx context.Context, username string, email string, password string) (*models.User, error) {
	ret := _m.Called(ctx, username, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.User, error)); ok {
		return rf(ctx, username, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.User); ok {
		r0 = rf(ctx, username, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, username, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetupTOTP provides a mock function with given fields: ctx, userID
func (_m *IAuthService) SetupTOTP(ctx context.Context, userID uuid.UUID) (string, string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetupTOTP")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) string); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// VerifyAndEnableTOTP provides a mock function with given fields: ctx, userID, code
func (_m *IAuthService) VerifyAndEnableTOTP(ctx context.Context, userID uuid.UUID, code string) error {
	ret := _m.Called(ctx, userID, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAndEnableTOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAuthService creates a new instance of IAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthService {
	mock := &IAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
