// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	types "github.com/WillieBam/support_copilot/backend/types"
	mock "github.com/stretchr/testify/mock"
)

// IClassificationStrategy is an autogenerated mock type for the IClassificationStrategy type
type IClassificationStrategy struct {
	mock.Mock
}

// Classify provides a mock function with given fields: prompt, history
func (_m *IClassificationStrategy) Classify(prompt string, history []types.HistoryMessage) (types.Intent, float64, bool) {
	ret := _m.Called(prompt, history)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 types.Intent
	var r1 float64
	var r2 bool
	if rf, ok := ret.Get(0).(func(string, []types.HistoryMessage) (types.Intent, float64, bool)); ok {
		return rf(prompt, history)
	}
	if rf, ok := ret.Get(0).(func(string, []types.HistoryMessage) types.Intent); ok {
		r0 = rf(prompt, history)
	} else {
		r0 = ret.Get(0).(types.Intent)
	}

	if rf, ok := ret.Get(1).(func(string, []types.HistoryMessage) float64); ok {
		r1 = rf(prompt, history)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(string, []types.HistoryMessage) bool); ok {
		r2 = rf(prompt, history)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// Name provides a mock function with no fields
func (_m *IClassificationStrategy) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewIClassificationStrategy creates a new instance of IClassificationStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClassificationStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClassificationStrategy {
	mock := &IClassificationStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
