// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/WillieBam/support_copilot/backend/types"
)

// ICommandHandler is an autogenerated mock type for the ICommandHandler type
type ICommandHandler struct {
	mock.Mock
}

// Command provides a mock function with no fields
func (_m *ICommandHandler) Command() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Command")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Description provides a mock function with no fields
func (_m *ICommandHandler) Description() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Handle provides a mock function with given fields: ctx, prompt
func (_m *ICommandHandler) Handle(ctx context.Context, prompt string) (*types.CommandResult, error) {
	ret := _m.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *types.CommandResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*types.CommandResult, error)); ok {
		return rf(ctx, prompt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *types.CommandResult); ok {
		r0 = rf(ctx, prompt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.CommandResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICommandHandler creates a new instance of ICommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICommandHandler {
	mock := &ICommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
