// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/WillieBam/support_copilot/backend/types/models"

	uuid "github.com/google/uuid"
)

// IConversationRepository is an autogenerated mock type for the IConversationRepository type
type IConversationRepository struct {
	mock.Mock
}

// CreateConversation provides a mock function with given fields: ctx, conv
func (_m *IConversationRepository) CreateConversation(ctx context.Context, conv *models.Conversation) error {
	ret := _m.Called(ctx, conv)

	if len(ret) == 0 {
		panic("no return value specified for CreateConversation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Conversation) error); ok {
		r0 = rf(ctx, conv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMessage provides a mock function with given fields: ctx, msg
func (_m *IConversationRepository) CreateMessage(ctx context.Context, msg *models.Message) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetConversationByID provides a mock function with given fields: ctx, id
func (_m *IConversationRepository) GetConversationByID(ctx context.Context, id uuid.UUID) (*models.Conversation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetConversationByID")
	}

	var r0 *models.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Conversation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Conversation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMessagesByConversation provides a mock function with given fields: ctx, convID
func (_m *IConversationRepository) ListMessagesByConversation(ctx context.Context, convID uuid.UUID) ([]models.Message, error) {
	ret := _m.Called(ctx, convID)

	if len(ret) == 0 {
		panic("no return value specified for ListMessagesByConversation")
	}

	var r0 []models.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Message, error)); ok {
		return rf(ctx, convID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Message); ok {
		r0 = rf(ctx, convID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, convID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTeamConversations provides a mock function with given fields: ctx, teamID, limit
func (_m *IConversationRepository) ListTeamConversations(ctx context.Context, teamID uuid.UUID, limit int) ([]models.Conversation, error) {
	ret := _m.Called(ctx, teamID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTeamConversations")
	}

	var r0 []models.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]models.Conversation, error)); ok {
		return rf(ctx, teamID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []models.Conversation); ok {
		r0 = rf(ctx, teamID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, teamID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConversationTitle provides a mock function with given fields: ctx, id, title
func (_m *IConversationRepository) UpdateConversationTitle(ctx context.Context, id uuid.UUID, title string) error {
	ret := _m.Called(ctx, id, title)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConversationTitle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, title)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIConversationRepository creates a new instance of IConversationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIConversationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IConversationRepository {
	mock := &IConversationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
