// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/WillieBam/support_copilot/backend/types"

	uuid "github.com/google/uuid"
)

// IDashboardService is an autogenerated mock type for the IDashboardService type
type IDashboardService struct {
	mock.Mock
}

// GetBreachedIncidents provides a mock function with given fields: ctx, requesterID, teamID, userScope, slaTargetMinutes, limit, offset
func (_m *IDashboardService) GetBreachedIncidents(ctx context.Context, requesterID uuid.UUID, teamID uuid.UUID, userScope string, slaTargetMinutes int, limit int, offset int) ([]types.BreachedIncident, error) {
	ret := _m.Called(ctx, requesterID, teamID, userScope, slaTargetMinutes, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBreachedIncidents")
	}

	var r0 []types.BreachedIncident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int, int, int) ([]types.BreachedIncident, error)); ok {
		return rf(ctx, requesterID, teamID, userScope, slaTargetMinutes, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int, int, int) []types.BreachedIncident); ok {
		r0 = rf(ctx, requesterID, teamID, userScope, slaTargetMinutes, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.BreachedIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, int, int, int) error); ok {
		r1 = rf(ctx, requesterID, teamID, userScope, slaTargetMinutes, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIncidentTrend provides a mock function with given fields: ctx, requesterID, teamID, userScope, timeframe
func (_m *IDashboardService) GetIncidentTrend(ctx context.Context, requesterID uuid.UUID, teamID uuid.UUID, userScope string, timeframe string) ([]types.IncidentTrendPoint, error) {
	ret := _m.Called(ctx, requesterID, teamID, userScope, timeframe)

	if len(ret) == 0 {
		panic("no return value specified for GetIncidentTrend")
	}

	var r0 []types.IncidentTrendPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) ([]types.IncidentTrendPoint, error)); ok {
		return rf(ctx, requesterID, teamID, userScope, timeframe)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) []types.IncidentTrendPoint); ok {
		r0 = rf(ctx, requesterID, teamID, userScope, timeframe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.IncidentTrendPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, requesterID, teamID, userScope, timeframe)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMTTR provides a mock function with given fields: ctx, requesterID, teamID, userScope, slaTargetMinutes
func (_m *IDashboardService) GetMTTR(ctx context.Context, requesterID uuid.UUID, teamID uuid.UUID, userScope string, slaTargetMinutes int) (*types.MTTRResult, error) {
	ret := _m.Called(ctx, requesterID, teamID, userScope, slaTargetMinutes)

	if len(ret) == 0 {
		panic("no return value specified for GetMTTR")
	}

	var r0 *types.MTTRResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int) (*types.MTTRResult, error)); ok {
		return rf(ctx, requesterID, teamID, userScope, slaTargetMinutes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int) *types.MTTRResult); ok {
		r0 = rf(ctx, requesterID, teamID, userScope, slaTargetMinutes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MTTRResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, int) error); ok {
		r1 = rf(ctx, requesterID, teamID, userScope, slaTargetMinutes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDashboardService creates a new instance of IDashboardService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDashboardService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDashboardService {
	mock := &IDashboardService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
