// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/WillieBam/support_copilot/backend/types"

	uuid "github.com/google/uuid"
)

// IDashboardRepository is an autogenerated mock type for the IDashboardRepository type
type IDashboardRepository struct {
	mock.Mock
}

// CountAllTeamsBreachedIncidents provides a mock function with given fields: ctx, slaTargetMinutes
func (_m *IDashboardRepository) CountAllTeamsBreachedIncidents(ctx context.Context, slaTargetMinutes int) (int, error) {
	ret := _m.Called(ctx, slaTargetMinutes)

	if len(ret) == 0 {
		panic("no return value specified for CountAllTeamsBreachedIncidents")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, slaTargetMinutes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, slaTargetMinutes)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, slaTargetMinutes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountBreachedIncidents provides a mock function with given fields: ctx, teamID, slaTargetMinutes
func (_m *IDashboardRepository) CountBreachedIncidents(ctx context.Context, teamID uuid.UUID, slaTargetMinutes int) (int, error) {
	ret := _m.Called(ctx, teamID, slaTargetMinutes)

	if len(ret) == 0 {
		panic("no return value specified for CountBreachedIncidents")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (int, error)); ok {
		return rf(ctx, teamID, slaTargetMinutes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) int); ok {
		r0 = rf(ctx, teamID, slaTargetMinutes)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, teamID, slaTargetMinutes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTeamsBreachedIncidents provides a mock function with given fields: ctx, slaTargetMinutes, limit, offset
func (_m *IDashboardRepository) GetAllTeamsBreachedIncidents(ctx context.Context, slaTargetMinutes int, limit int, offset int) ([]types.BreachedIncident, error) {
	ret := _m.Called(ctx, slaTargetMinutes, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTeamsBreachedIncidents")
	}

	var r0 []types.BreachedIncident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]types.BreachedIncident, error)); ok {
		return rf(ctx, slaTargetMinutes, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []types.BreachedIncident); ok {
		r0 = rf(ctx, slaTargetMinutes, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.BreachedIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, slaTargetMinutes, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTeamsIncidentTrend provides a mock function with given fields: ctx, timeframe
func (_m *IDashboardRepository) GetAllTeamsIncidentTrend(ctx context.Context, timeframe string) ([]types.IncidentTrendPoint, error) {
	ret := _m.Called(ctx, timeframe)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTeamsIncidentTrend")
	}

	var r0 []types.IncidentTrendPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]types.IncidentTrendPoint, error)); ok {
		return rf(ctx, timeframe)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []types.IncidentTrendPoint); ok {
		r0 = rf(ctx, timeframe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.IncidentTrendPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, timeframe)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTeamsMTTRStats provides a mock function with given fields: ctx
func (_m *IDashboardRepository) GetAllTeamsMTTRStats(ctx context.Context) (float64, int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTeamsMTTRStats")
	}

	var r0 float64
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (float64, int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) float64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetBreachedIncidents provides a mock function with given fields: ctx, teamID, slaTargetMinutes, limit, offset
func (_m *IDashboardRepository) GetBreachedIncidents(ctx context.Context, teamID uuid.UUID, slaTargetMinutes int, limit int, offset int) ([]types.BreachedIncident, error) {
	ret := _m.Called(ctx, teamID, slaTargetMinutes, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetBreachedIncidents")
	}

	var r0 []types.BreachedIncident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, int) ([]types.BreachedIncident, error)); ok {
		return rf(ctx, teamID, slaTargetMinutes, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, int) []types.BreachedIncident); ok {
		r0 = rf(ctx, teamID, slaTargetMinutes, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.BreachedIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int, int) error); ok {
		r1 = rf(ctx, teamID, slaTargetMinutes, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIncidentTrend provides a mock function with given fields: ctx, teamID, timeframe
func (_m *IDashboardRepository) GetIncidentTrend(ctx context.Context, teamID uuid.UUID, timeframe string) ([]types.IncidentTrendPoint, error) {
	ret := _m.Called(ctx, teamID, timeframe)

	if len(ret) == 0 {
		panic("no return value specified for GetIncidentTrend")
	}

	var r0 []types.IncidentTrendPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]types.IncidentTrendPoint, error)); ok {
		return rf(ctx, teamID, timeframe)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []types.IncidentTrendPoint); ok {
		r0 = rf(ctx, teamID, timeframe)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.IncidentTrendPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, teamID, timeframe)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMTTRStats provides a mock function with given fields: ctx, teamID
func (_m *IDashboardRepository) GetMTTRStats(ctx context.Context, teamID uuid.UUID) (float64, int, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetMTTRStats")
	}

	var r0 float64
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (float64, int, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) float64); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) int); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, teamID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewIDashboardRepository creates a new instance of IDashboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDashboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDashboardRepository {
	mock := &IDashboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
