// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	requests "github.com/WillieBam/support_copilot/backend/types/requests"

	types "github.com/WillieBam/support_copilot/backend/types"
)

// ILLMClient is an autogenerated mock type for the ILLMClient type
type ILLMClient struct {
	mock.Mock
}

// QueryStreamWithTools provides a mock function with given fields: ctx, req, streamChan
func (_m *ILLMClient) QueryStreamWithTools(ctx context.Context, req requests.LLMChatRequest, streamChan chan<- types.StreamEvent) (*requests.LLMMessage, error) {
	ret := _m.Called(ctx, req, streamChan)

	if len(ret) == 0 {
		panic("no return value specified for QueryStreamWithTools")
	}

	var r0 *requests.LLMMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.LLMChatRequest, chan<- types.StreamEvent) (*requests.LLMMessage, error)); ok {
		return rf(ctx, req, streamChan)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requests.LLMChatRequest, chan<- types.StreamEvent) *requests.LLMMessage); ok {
		r0 = rf(ctx, req, streamChan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*requests.LLMMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, requests.LLMChatRequest, chan<- types.StreamEvent) error); ok {
		r1 = rf(ctx, req, streamChan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewILLMClient creates a new instance of ILLMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILLMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILLMClient {
	mock := &ILLMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
