// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	requests "github.com/WillieBam/support_copilot/backend/types/requests"
)

// IMCP2Client is an autogenerated mock type for the IMCP2Client type
type IMCP2Client struct {
	mock.Mock
}

// CreateRunbook provides a mock function with given fields: ctx, args
func (_m *IMCP2Client) CreateRunbook(ctx context.Context, args requests.MCP2CreateRunbookArgs) (string, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for CreateRunbook")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2CreateRunbookArgs) (string, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2CreateRunbookArgs) string); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, requests.MCP2CreateRunbookArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeprecateRunbook provides a mock function with given fields: ctx, args
func (_m *IMCP2Client) DeprecateRunbook(ctx context.Context, args requests.MCP2DeprecateRunbookArgs) (string, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for DeprecateRunbook")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2DeprecateRunbookArgs) (string, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2DeprecateRunbookArgs) string); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, requests.MCP2DeprecateRunbookArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIncident provides a mock function with given fields: ctx, args
func (_m *IMCP2Client) GetIncident(ctx context.Context, args requests.MCP2GetIncidentArgs) (string, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetIncident")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2GetIncidentArgs) (string, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2GetIncidentArgs) string); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, requests.MCP2GetIncidentArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunbook provides a mock function with given fields: ctx, args
func (_m *IMCP2Client) GetRunbook(ctx context.Context, args requests.MCP2GetRunbookArgs) (string, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for GetRunbook")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2GetRunbookArgs) (string, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2GetRunbookArgs) string); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, requests.MCP2GetRunbookArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListIncidents provides a mock function with given fields: ctx, args
func (_m *IMCP2Client) ListIncidents(ctx context.Context, args requests.MCP2ListIncidentsArgs) (string, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListIncidents")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2ListIncidentsArgs) (string, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2ListIncidentsArgs) string); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, requests.MCP2ListIncidentsArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRunbooks provides a mock function with given fields: ctx, args
func (_m *IMCP2Client) ListRunbooks(ctx context.Context, args requests.MCP2ListRunbooksArgs) (string, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ListRunbooks")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2ListRunbooksArgs) (string, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2ListRunbooksArgs) string); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, requests.MCP2ListRunbooksArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRunbook provides a mock function with given fields: ctx, args
func (_m *IMCP2Client) UpdateRunbook(ctx context.Context, args requests.MCP2UpdateRunbookArgs) (string, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunbook")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2UpdateRunbookArgs) (string, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requests.MCP2UpdateRunbookArgs) string); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, requests.MCP2UpdateRunbookArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIMCP2Client creates a new instance of IMCP2Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMCP2Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMCP2Client {
	mock := &IMCP2Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
