// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/WillieBam/support_copilot/backend/types/models"

	uuid "github.com/google/uuid"
)

// ITeamService is an autogenerated mock type for the ITeamService type
type ITeamService struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: ctx, requesterID, teamID, userID
func (_m *ITeamService) AddMember(ctx context.Context, requesterID uuid.UUID, teamID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, requesterID, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, requesterID, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignIncident provides a mock function with given fields: ctx, requesterID, teamID, incidentID, title, status, details
func (_m *ITeamService) AssignIncident(ctx context.Context, requesterID uuid.UUID, teamID uuid.UUID, incidentID uuid.UUID, title string, status string, details string) (*models.TeamIncident, error) {
	ret := _m.Called(ctx, requesterID, teamID, incidentID, title, status, details)

	if len(ret) == 0 {
		panic("no return value specified for AssignIncident")
	}

	var r0 *models.TeamIncident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string, string, string) (*models.TeamIncident, error)); ok {
		return rf(ctx, requesterID, teamID, incidentID, title, status, details)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string, string, string) *models.TeamIncident); ok {
		r0 = rf(ctx, requesterID, teamID, incidentID, title, status, details)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string, string, string) error); ok {
		r1 = rf(ctx, requesterID, teamID, incidentID, title, status, details)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRunbook provides a mock function with given fields: ctx, teamID, incidentID, title, content
func (_m *ITeamService) CreateRunbook(ctx context.Context, teamID uuid.UUID, incidentID uuid.UUID, title string, content string) (*models.Runbook, error) {
	ret := _m.Called(ctx, teamID, incidentID, title, content)

	if len(ret) == 0 {
		panic("no return value specified for CreateRunbook")
	}

	var r0 *models.Runbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) (*models.Runbook, error)); ok {
		return rf(ctx, teamID, incidentID, title, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) *models.Runbook); ok {
		r0 = rf(ctx, teamID, incidentID, title, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Runbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, teamID, incidentID, title, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTeam provides a mock function with given fields: ctx, teamName, creatorID
func (_m *ITeamService) CreateTeam(ctx context.Context, teamName string, creatorID uuid.UUID) (*models.Team, error) {
	ret := _m.Called(ctx, teamName, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*models.Team, error)); ok {
		return rf(ctx, teamName, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *models.Team); ok {
		r0 = rf(ctx, teamName, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, teamName, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTeam provides a mock function with given fields: ctx, userScope, teamID
func (_m *ITeamService) DeleteTeam(ctx context.Context, userScope string, teamID uuid.UUID) error {
	ret := _m.Called(ctx, userScope, teamID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = rf(ctx, userScope, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeprecateRunbook provides a mock function with given fields: ctx, runbookID
func (_m *ITeamService) DeprecateRunbook(ctx context.Context, runbookID uuid.UUID) (*models.Runbook, error) {
	ret := _m.Called(ctx, runbookID)

	if len(ret) == 0 {
		panic("no return value specified for DeprecateRunbook")
	}

	var r0 *models.Runbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Runbook, error)); ok {
		return rf(ctx, runbookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Runbook); ok {
		r0 = rf(ctx, runbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Runbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, runbookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIncident provides a mock function with given fields: ctx, requesterID, incidentID
func (_m *ITeamService) GetIncident(ctx context.Context, requesterID uuid.UUID, incidentID uuid.UUID) (*models.TeamIncident, error) {
	ret := _m.Called(ctx, requesterID, incidentID)

	if len(ret) == 0 {
		panic("no return value specified for GetIncident")
	}

	var r0 *models.TeamIncident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.TeamIncident, error)); ok {
		return rf(ctx, requesterID, incidentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.TeamIncident); ok {
		r0 = rf(ctx, requesterID, incidentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, requesterID, incidentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIncidentContext provides a mock function with given fields: ctx, teamIncidentID
func (_m *ITeamService) GetIncidentContext(ctx context.Context, teamIncidentID uuid.UUID) (*models.TeamIncident, []models.Alert, error) {
	ret := _m.Called(ctx, teamIncidentID)

	if len(ret) == 0 {
		panic("no return value specified for GetIncidentContext")
	}

	var r0 *models.TeamIncident
	var r1 []models.Alert
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.TeamIncident, []models.Alert, error)); ok {
		return rf(ctx, teamIncidentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.TeamIncident); ok {
		r0 = rf(ctx, teamIncidentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) []models.Alert); ok {
		r1 = rf(ctx, teamIncidentID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]models.Alert)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, teamIncidentID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetRunbook provides a mock function with given fields: ctx, runbookID
func (_m *ITeamService) GetRunbook(ctx context.Context, runbookID uuid.UUID) (*models.Runbook, error) {
	ret := _m.Called(ctx, runbookID)

	if len(ret) == 0 {
		panic("no return value specified for GetRunbook")
	}

	var r0 *models.Runbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Runbook, error)); ok {
		return rf(ctx, runbookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Runbook); ok {
		r0 = rf(ctx, runbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Runbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, runbookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeam provides a mock function with given fields: ctx, teamID
func (_m *ITeamService) GetTeam(ctx context.Context, teamID uuid.UUID) (*models.Team, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Team, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Team); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamInstruction provides a mock function with given fields: ctx, requesterID, teamID
func (_m *ITeamService) GetTeamInstruction(ctx context.Context, requesterID uuid.UUID, teamID uuid.UUID) (*models.Instruction, []models.InstructionLog, error) {
	ret := _m.Called(ctx, requesterID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamInstruction")
	}

	var r0 *models.Instruction
	var r1 []models.InstructionLog
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.Instruction, []models.InstructionLog, error)); ok {
		return rf(ctx, requesterID, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.Instruction); ok {
		r0 = rf(ctx, requesterID, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Instruction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) []models.InstructionLog); ok {
		r1 = rf(ctx, requesterID, teamID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]models.InstructionLog)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r2 = rf(ctx, requesterID, teamID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetUserTeams provides a mock function with given fields: ctx, userID
func (_m *ITeamService) GetUserTeams(ctx context.Context, userID uuid.UUID) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTeams")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListIncidents provides a mock function with given fields: ctx, requesterID, teamID
func (_m *ITeamService) ListIncidents(ctx context.Context, requesterID uuid.UUID, teamID uuid.UUID) ([]models.TeamIncident, error) {
	ret := _m.Called(ctx, requesterID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for ListIncidents")
	}

	var r0 []models.TeamIncident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.TeamIncident, error)); ok {
		return rf(ctx, requesterID, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.TeamIncident); ok {
		r0 = rf(ctx, requesterID, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, requesterID, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMembers provides a mock function with given fields: ctx, requesterID, teamID
func (_m *ITeamService) ListMembers(ctx context.Context, requesterID uuid.UUID, teamID uuid.UUID) ([]models.TeamMember, error) {
	ret := _m.Called(ctx, requesterID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []models.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.TeamMember, error)); ok {
		return rf(ctx, requesterID, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.TeamMember); ok {
		r0 = rf(ctx, requesterID, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, requesterID, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRunbooks provides a mock function with given fields: ctx, teamID, status
func (_m *ITeamService) ListRunbooks(ctx context.Context, teamID uuid.UUID, status string) ([]models.Runbook, error) {
	ret := _m.Called(ctx, teamID, status)

	if len(ret) == 0 {
		panic("no return value specified for ListRunbooks")
	}

	var r0 []models.Runbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]models.Runbook, error)); ok {
		return rf(ctx, teamID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []models.Runbook); ok {
		r0 = rf(ctx, teamID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Runbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, teamID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: ctx, requesterID, teamID, userID
func (_m *ITeamService) RemoveMember(ctx context.Context, requesterID uuid.UUID, teamID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, requesterID, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, requesterID, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveTeamInstruction provides a mock function with given fields: ctx, requesterID, teamID, details
func (_m *ITeamService) SaveTeamInstruction(ctx context.Context, requesterID uuid.UUID, teamID uuid.UUID, details string) (*models.Instruction, error) {
	ret := _m.Called(ctx, requesterID, teamID, details)

	if len(ret) == 0 {
		panic("no return value specified for SaveTeamInstruction")
	}

	var r0 *models.Instruction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*models.Instruction, error)); ok {
		return rf(ctx, requesterID, teamID, details)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *models.Instruction); ok {
		r0 = rf(ctx, requesterID, teamID, details)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Instruction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, requesterID, teamID, details)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateIncidentStatus provides a mock function with given fields: ctx, requesterID, incidentID, newStatus, title, details
func (_m *ITeamService) UpdateIncidentStatus(ctx context.Context, requesterID uuid.UUID, incidentID uuid.UUID, newStatus string, title string, details string) (*models.TeamIncident, error) {
	ret := _m.Called(ctx, requesterID, incidentID, newStatus, title, details)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIncidentStatus")
	}

	var r0 *models.TeamIncident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, string) (*models.TeamIncident, error)); ok {
		return rf(ctx, requesterID, incidentID, newStatus, title, details)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, string) *models.TeamIncident); ok {
		r0 = rf(ctx, requesterID, incidentID, newStatus, title, details)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string, string) error); ok {
		r1 = rf(ctx, requesterID, incidentID, newStatus, title, details)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRunbook provides a mock function with given fields: ctx, runbookID, title, content
func (_m *ITeamService) UpdateRunbook(ctx context.Context, runbookID uuid.UUID, title string, content string) (*models.Runbook, error) {
	ret := _m.Called(ctx, runbookID, title, content)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunbook")
	}

	var r0 *models.Runbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*models.Runbook, error)); ok {
		return rf(ctx, runbookID, title, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *models.Runbook); ok {
		r0 = rf(ctx, runbookID, title, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Runbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, runbookID, title, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITeamService creates a new instance of ITeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITeamService {
	mock := &ITeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
