// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/WillieBam/support_copilot/backend/types/models"

	uuid "github.com/google/uuid"
)

// ITeamRepository is an autogenerated mock type for the ITeamRepository type
type ITeamRepository struct {
	mock.Mock
}

// AddTeamMember provides a mock function with given fields: ctx, member
func (_m *ITeamRepository) AddTeamMember(ctx context.Context, member *models.TeamMember) error {
	ret := _m.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for AddTeamMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TeamMember) error); ok {
		r0 = rf(ctx, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignTeamIncident provides a mock function with given fields: ctx, incident
func (_m *ITeamRepository) AssignTeamIncident(ctx context.Context, incident *models.TeamIncident) error {
	ret := _m.Called(ctx, incident)

	if len(ret) == 0 {
		panic("no return value specified for AssignTeamIncident")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TeamIncident) error); ok {
		r0 = rf(ctx, incident)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRunbook provides a mock function with given fields: ctx, runbook
func (_m *ITeamRepository) CreateRunbook(ctx context.Context, runbook *models.Runbook) error {
	ret := _m.Called(ctx, runbook)

	if len(ret) == 0 {
		panic("no return value specified for CreateRunbook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Runbook) error); ok {
		r0 = rf(ctx, runbook)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTeamWithOwner provides a mock function with given fields: ctx, team, ownerID
func (_m *ITeamRepository) CreateTeamWithOwner(ctx context.Context, team *models.Team, ownerID uuid.UUID) error {
	ret := _m.Called(ctx, team, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeamWithOwner")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Team, uuid.UUID) error); ok {
		r0 = rf(ctx, team, ownerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTeam provides a mock function with given fields: ctx, teamID
func (_m *ITeamRepository) DeleteTeam(ctx context.Context, teamID uuid.UUID) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeprecateRunbook provides a mock function with given fields: ctx, runbookID
func (_m *ITeamRepository) DeprecateRunbook(ctx context.Context, runbookID uuid.UUID) (*models.Runbook, error) {
	ret := _m.Called(ctx, runbookID)

	if len(ret) == 0 {
		panic("no return value specified for DeprecateRunbook")
	}

	var r0 *models.Runbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Runbook, error)); ok {
		return rf(ctx, runbookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Runbook); ok {
		r0 = rf(ctx, runbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Runbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, runbookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIncidentContext provides a mock function with given fields: ctx, teamIncidentID
func (_m *ITeamRepository) GetIncidentContext(ctx context.Context, teamIncidentID uuid.UUID) (*models.TeamIncident, []models.Alert, error) {
	ret := _m.Called(ctx, teamIncidentID)

	if len(ret) == 0 {
		panic("no return value specified for GetIncidentContext")
	}

	var r0 *models.TeamIncident
	var r1 []models.Alert
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.TeamIncident, []models.Alert, error)); ok {
		return rf(ctx, teamIncidentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.TeamIncident); ok {
		r0 = rf(ctx, teamIncidentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) []models.Alert); ok {
		r1 = rf(ctx, teamIncidentID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]models.Alert)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, teamIncidentID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetMemberRole provides a mock function with given fields: ctx, teamID, userID
func (_m *ITeamRepository) GetMemberRole(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRole")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (string, error)); ok {
		return rf(ctx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) string); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunbookByID provides a mock function with given fields: ctx, runbookID
func (_m *ITeamRepository) GetRunbookByID(ctx context.Context, runbookID uuid.UUID) (*models.Runbook, error) {
	ret := _m.Called(ctx, runbookID)

	if len(ret) == 0 {
		panic("no return value specified for GetRunbookByID")
	}

	var r0 *models.Runbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Runbook, error)); ok {
		return rf(ctx, runbookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Runbook); ok {
		r0 = rf(ctx, runbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Runbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, runbookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunbookLogs provides a mock function with given fields: ctx, runbookID
func (_m *ITeamRepository) GetRunbookLogs(ctx context.Context, runbookID uuid.UUID) ([]models.RunbookLog, error) {
	ret := _m.Called(ctx, runbookID)

	if len(ret) == 0 {
		panic("no return value specified for GetRunbookLogs")
	}

	var r0 []models.RunbookLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.RunbookLog, error)); ok {
		return rf(ctx, runbookID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.RunbookLog); ok {
		r0 = rf(ctx, runbookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RunbookLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, runbookID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunbooksByIncidentID provides a mock function with given fields: ctx, incidentID
func (_m *ITeamRepository) GetRunbooksByIncidentID(ctx context.Context, incidentID uuid.UUID) ([]models.Runbook, error) {
	ret := _m.Called(ctx, incidentID)

	if len(ret) == 0 {
		panic("no return value specified for GetRunbooksByIncidentID")
	}

	var r0 []models.Runbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Runbook, error)); ok {
		return rf(ctx, incidentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Runbook); ok {
		r0 = rf(ctx, incidentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Runbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, incidentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamByID provides a mock function with given fields: ctx, teamID
func (_m *ITeamRepository) GetTeamByID(ctx context.Context, teamID uuid.UUID) (*models.Team, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByID")
	}

	var r0 *models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Team, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Team); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamIncidentByID provides a mock function with given fields: ctx, incidentID
func (_m *ITeamRepository) GetTeamIncidentByID(ctx context.Context, incidentID uuid.UUID) (*models.TeamIncident, error) {
	ret := _m.Called(ctx, incidentID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamIncidentByID")
	}

	var r0 *models.TeamIncident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.TeamIncident, error)); ok {
		return rf(ctx, incidentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.TeamIncident); ok {
		r0 = rf(ctx, incidentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, incidentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamInstruction provides a mock function with given fields: ctx, teamID
func (_m *ITeamRepository) GetTeamInstruction(ctx context.Context, teamID uuid.UUID) (*models.Instruction, []models.InstructionLog, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamInstruction")
	}

	var r0 *models.Instruction
	var r1 []models.InstructionLog
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Instruction, []models.InstructionLog, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Instruction); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Instruction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) []models.InstructionLog); ok {
		r1 = rf(ctx, teamID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]models.InstructionLog)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, teamID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetUserWithTeamsByID provides a mock function with given fields: ctx, userID
func (_m *ITeamRepository) GetUserWithTeamsByID(ctx context.Context, userID uuid.UUID) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithTeamsByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllTeams provides a mock function with given fields: ctx
func (_m *ITeamRepository) ListAllTeams(ctx context.Context) ([]models.Team, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllTeams")
	}

	var r0 []models.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Team, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Team); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRunbooks provides a mock function with given fields: ctx, teamID, status
func (_m *ITeamRepository) ListRunbooks(ctx context.Context, teamID uuid.UUID, status string) ([]models.Runbook, error) {
	ret := _m.Called(ctx, teamID, status)

	if len(ret) == 0 {
		panic("no return value specified for ListRunbooks")
	}

	var r0 []models.Runbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]models.Runbook, error)); ok {
		return rf(ctx, teamID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []models.Runbook); ok {
		r0 = rf(ctx, teamID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Runbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, teamID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTeamIncidents provides a mock function with given fields: ctx, teamID
func (_m *ITeamRepository) ListTeamIncidents(ctx context.Context, teamID uuid.UUID) ([]models.TeamIncident, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for ListTeamIncidents")
	}

	var r0 []models.TeamIncident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.TeamIncident, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.TeamIncident); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTeamMembers provides a mock function with given fields: ctx, teamID
func (_m *ITeamRepository) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]models.TeamMember, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for ListTeamMembers")
	}

	var r0 []models.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.TeamMember, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.TeamMember); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveTeamMember provides a mock function with given fields: ctx, teamID, userID
func (_m *ITeamRepository) RemoveTeamMember(ctx context.Context, teamID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTeamMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveTeamInstruction provides a mock function with given fields: ctx, instruction, log
func (_m *ITeamRepository) SaveTeamInstruction(ctx context.Context, instruction *models.Instruction, log *models.InstructionLog) error {
	ret := _m.Called(ctx, instruction, log)

	if len(ret) == 0 {
		panic("no return value specified for SaveTeamInstruction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Instruction, *models.InstructionLog) error); ok {
		r0 = rf(ctx, instruction, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRunbook provides a mock function with given fields: ctx, runbookID, title, content, log
func (_m *ITeamRepository) UpdateRunbook(ctx context.Context, runbookID uuid.UUID, title string, content string, log *models.RunbookLog) (*models.Runbook, error) {
	ret := _m.Called(ctx, runbookID, title, content, log)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunbook")
	}

	var r0 *models.Runbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, *models.RunbookLog) (*models.Runbook, error)); ok {
		return rf(ctx, runbookID, title, content, log)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, *models.RunbookLog) *models.Runbook); ok {
		r0 = rf(ctx, runbookID, title, content, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Runbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, *models.RunbookLog) error); ok {
		r1 = rf(ctx, runbookID, title, content, log)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTeamIncidentStatus provides a mock function with given fields: ctx, history, updatedInc
func (_m *ITeamRepository) UpdateTeamIncidentStatus(ctx context.Context, history *models.IncidentStatusHistory, updatedInc *models.TeamIncident) error {
	ret := _m.Called(ctx, history, updatedInc)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeamIncidentStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.IncidentStatusHistory, *models.TeamIncident) error); ok {
		r0 = rf(ctx, history, updatedInc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewITeamRepository creates a new instance of ITeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITeamRepository {
	mock := &ITeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
