// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	requests "github.com/WillieBam/support_copilot/backend/types/requests"
)

// ITool is an autogenerated mock type for the ITool type
type ITool struct {
	mock.Mock
}

// Definition provides a mock function with no fields
func (_m *ITool) Definition() requests.LLMTool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Definition")
	}

	var r0 requests.LLMTool
	if rf, ok := ret.Get(0).(func() requests.LLMTool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(requests.LLMTool)
	}

	return r0
}

// Execute provides a mock function with given fields: ctx, rawArgs
func (_m *ITool) Execute(ctx context.Context, rawArgs string) (string, error) {
	ret := _m.Called(ctx, rawArgs)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, rawArgs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, rawArgs)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rawArgs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with no fields
func (_m *ITool) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewITool creates a new instance of ITool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITool(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITool {
	mock := &ITool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
