// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/WillieBam/support_copilot/backend/types/models"

	uuid "github.com/google/uuid"
)

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

// DeactivateUser provides a mock function with given fields: ctx, requesterID, targetUserID
func (_m *IUserService) DeactivateUser(ctx context.Context, requesterID uuid.UUID, targetUserID uuid.UUID) error {
	ret := _m.Called(ctx, requesterID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, requesterID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByFirebaseUID provides a mock function with given fields: ctx, firebaseUid
func (_m *IUserService) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (*models.User, error) {
	ret := _m.Called(ctx, firebaseUid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByFirebaseUID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, firebaseUid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, firebaseUid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, firebaseUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchUsers provides a mock function with given fields: ctx, query, limit
func (_m *IUserService) SearchUsers(ctx context.Context, query string, limit int) ([]models.User, error) {
	ret := _m.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]models.User, error)); ok {
		return rf(ctx, query, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []models.User); ok {
		r0 = rf(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUserService creates a new instance of IUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserService {
	mock := &IUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
